paths: #estandarizamos las rutas para no tener que repetirlas en todas las funciones
  raw: "raw"
  warehouse: "warehouse"
  dim: "warehouse/dim"
  fact: "warehouse/fact"

business_rules: #se usa en el fact de nps
  nps:
    detractor_max: 6
    passive_min: 7
    passive_max: 8
    promoter_min: 9
